### ISSUE TITLE
macOS installation

### ISSUE THREAD

**Issue by czodrowskilab** [josejimenezluna/molgrad#6]
How do I install your lovely tool under macOS?

I'm receiving this message:
```
Solving environment: failed

ResolvePackageNotFound: 
  - cudatoolkit=10.1
  - dgllife=0.2.3
  - dgl-cuda10.1=0.4.3post2
```

**Comment by josejimenezluna** [comment]
Dear @czodrowskilab,

Similarly to #7 , I'll see if I can write an OS X-specific environment file and let you know.

Cheers,

**Comment by josejimenezluna** [comment]
See issue #7 for more details.

**Comment by czodrowskilab** [comment]
I got this message: 
`ResolvePackageNotFound: 
  - dgllife=0.2.3`

**Comment by josejimenezluna** [comment]
Apparently that specific dependency version is not available for OS X builds. 

https://anaconda.org/dglteam/dgllife/files?version=0.2.3

However, 0.2.5 seems to be available. Could you please modify the environment file and try the installation on a mac to see whether that works?

Cheers,
