### ISSUE TITLE
libcuda.so error

### ISSUE THREAD

**Issue by czodrowskilab** [josejimenezluna/molgrad#7]
I just installed molgrad on a Linux VM w/o any GPU.

I'm running into this error:
`OSError: libcuda.so.1: cannot open shared object file: No such file or directory`
when executing
` python molgrad/molgrad/main.py --help`

According to the molgrad readme, a CUDA-capable GPU is encouraged but not required.

**Comment by josejimenezluna** [comment]
Dear @czodrowskilab,

Thanks for taking an interest in this. While a CUDA GPU is not required, CUDA libraries need to be found in the host system.

I'll look into this to see if I can provide a separate environment file for CPU-only dependency installations and come back to you.

Cheers,

**Comment by czodrowskilab** [comment]
Dear @josejimenezluna , next week friday we are running our group meeting in which i would like to present your tool.
do you think it would be feasible for you to come up with a quick until then? that would be really awesome and highly appreciated!

cheers, @czodrowskilab

**Comment by josejimenezluna** [comment]
Dear @czodrowskilab,

A new `environment_cpu.yml` file has been pushed to the master branch. It works on a CPU-only Linux installation and it should also work under OS X, although I don't have a test bench to test the latter at the moment.

Let me know if this is solved,

**Comment by czodrowskilab** [comment]
Cool, thanks a lot!

The Linux installation went smoothly, but now I'm facing this issue in the notebook "herg_motif":
  
`AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
`

**Comment by josejimenezluna** [comment]
Hi,

Some old cuda-specific code managed to sneak its way into the production code. I've pushed some changes that should fix them and tested them on a clean cpu-only vagrant ubuntu VM. 

Let me know if you encounter other issues :+1:
