### ISSUE TITLE
importances_scaled.pt

### ISSUE THREAD

**Issue by czodrowskilab** [josejimenezluna/molgrad#8]
I'm running the notebook `herg_global_analysis` and run into this error:

`FileNotFoundError: [Errno 2] No such file or directory: '[...]importances_scaled.pt'`

This files seems not be part of the data archive (I only found  `importances.pt` ) or am I wrong?

**Comment by josejimenezluna** [comment]
Hi, thanks for noticing this

The `data.tar.gz` tarball has been updated with the missing file.

**Comment by czodrowskilab** [comment]
`(molgrad) p:data profpaul$ ls -lrt
total 45856
drwxr-x---   18 profpaul  staff       576  9 Sep  2020 raw
-rw-r-----    1 profpaul  staff      2948  9 Sep  2020 guide.pt
-rw-r-----    1 profpaul  staff       677  9 Sep  2020 failed.pt
-rw-r-----    1 profpaul  staff         0  9 Sep  2020 __init__.py
drwxr-x---   19 profpaul  staff       608  9 Sep  2020 processed
drwxr-x---   81 profpaul  staff      2592  9 Okt  2020 ppb
drwxr-x---   75 profpaul  staff      2400  9 Okt  2020 caco2
drwxr-x---  102 profpaul  staff      3264  9 Okt  2020 herg
drwxr-x---   81 profpaul  staff      2592 16 Okt  2020 cyp
-rw-r--r--    1 profpaul  staff  23466406 18 Okt  2020 importances.pt
drwxr-xr-x   35 profpaul  staff      1120 21 Jun 15:13 examples`

I just downloaded it but still cannot find `importances_scaled.pt`

Did the polybox link change?

**Comment by josejimenezluna** [comment]
The download link should be the same

```bash
(base) hawk31@xps:~$ mkdir download_trial
(base) hawk31@xps:~$ cd download_trial/
(base) hawk31@xps:~/download_trial$ wget https://polybox.ethz.ch/index.php/s/K0orABbeJmwOUEh/download -O data.tar.gz
--2021-06-22 14:15:48--  https://polybox.ethz.ch/index.php/s/K0orABbeJmwOUEh/download
Resolving polybox.ethz.ch (polybox.ethz.ch)... 129.132.71.243
Connecting to polybox.ethz.ch (polybox.ethz.ch)|129.132.71.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1389855063 (1.3G) [application/x-gzip]
Saving to: ‘data.tar.gz’

data.tar.gz             100%[==============================>]   1.29G  10.2MB/s    in 2m 10s  

2021-06-22 14:17:58 (10.2 MB/s) - ‘data.tar.gz’ saved [1389855063/1389855063]

(base) hawk31@xps:~/download_trial$ tar -xf data.tar.gz 
(base) hawk31@xps:~/download_trial$ ll data/importances*
-rw-rw-r-- 1 hawk31 hawk31 23466406 Oct 18  2020 data/importances.pt
-rw-rw---- 1 hawk31 hawk31 23466354 Oct 29  2020 data/importances_scaled.pt
(base) hawk31@xps:~/download_trial$ 

```
