### ISSUE TITLE
Prediction output value? (and a small typo)

### ISSUE THREAD

**Issue by miquelduranfrigola** [josejimenezluna/molgrad#9]
Hi! Thanks for a wonderful repository.
I wonder if there is a way to get as an output the prediction value (e.g. activity against CYP3A4) as well as the explanations as currently available.
Thanks!

PS: In the README file, there is a typo on the download data snippet: wget hhttps...

**Comment by josejimenezluna** [comment]
Dear @miquelduranfrigola,

Many thanks for taking an interest in this repo and for spotting the typo! In the `prod.py` file there is a small function that does precisely what I believe you're asking. It takes the molecule of interest as well as the loaded GNN model, like the examples on the notebooks. 

https://github.com/josejimenezluna/molgrad/blob/4b14094454e8e3dc59d15bf628356b5abace84e1/molgrad/prod.py#L79-L84

Let me know if this helps

**Comment by miquelduranfrigola** [comment]
Gracias!
This is exactly what I needed.
